[package]
name = "web-push"
description = "Web push notification client with support for http-ece encryption and VAPID authentication."
version = "0.11.0"
authors = ["Julius de Bruijn <julius+github@nauk.io>", "Andrew Ealovega <Andrew@Ealovega.dev>"]
license = "Apache-2.0"
homepage = "https://github.com/pimeys/rust-web-push"
repository = "https://github.com/pimeys/rust-web-push"
documentation = "https://docs.rs/web-push/"
readme = "README.md"
keywords = ["web-push", "http-ece", "vapid"]
categories = ["web-programming", "asynchronous"]
rust-version = "1.80"
edition = "2021"

[features]
default = ["hyper-client"]
hyper-client = ["hyper", "hyper-tls", "hyper-util", "http-body-util"]

[dependencies]
hyper = { version = "1.7", optional = true }
hyper-util = { version = "0.1", features = ["client", "client-legacy", "http1"], optional = true }
http-body-util = { version = "0.1", optional = true }
hyper-tls = { version = "0.6", optional = true }
http = "1.3"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
jwt-simple = { version = "0.12.11", default-features = false, features = ["pure-rust"] }
ece = "2.2"
pem = "3.0.4"
sec1 = "0.7"
chrono = "0.4"
log = "0.4"
async-trait = "0.1"
ct-codecs = "1.1.3"

[dev-dependencies]
regex = "1.5"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
